name: Bug Report
description: Report a bug or unexpected behavior in Cognitive Mesh
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill out the sections below to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run command '...'
        2. Call method '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages and stack traces if applicable.
    validations:
      required: true

  - type: dropdown
    id: layer
    attributes:
      label: Architecture Layer
      description: Which layer is affected?
      multiple: true
      options:
        - FoundationLayer
        - ReasoningLayer
        - MetacognitiveLayer
        - AgencyLayer
        - BusinessApplications
        - Infrastructure / CI/CD
        - Unknown
    validations:
      required: true

  - type: input
    id: dotnet-version
    attributes:
      label: .NET Version
      description: Output of `dotnet --version`
      placeholder: "9.0.100"
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
        - Docker
        - Other
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Paste any relevant log output. This will be automatically formatted as code.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (configuration, environment, workarounds tried).
    validations:
      required: false
