name: Feature Request
description: Suggest a new feature or enhancement for Cognitive Mesh
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Please describe your idea so we can evaluate and prioritize it.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you would like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you have considered.
    validations:
      required: false

  - type: dropdown
    id: layer
    attributes:
      label: Architecture Layer
      description: Which layer would this feature affect?
      multiple: true
      options:
        - FoundationLayer
        - ReasoningLayer
        - MetacognitiveLayer
        - AgencyLayer
        - BusinessApplications
        - Infrastructure / CI/CD
        - New / Cross-cutting
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or references related to the feature request.
    validations:
      required: false
