namespace AgencyLayer.Orchestration.Ports;

/// <summary>
/// Role of an LLM in the dual pattern.
/// </summary>
public enum LLMRole
{
    /// <summary>Planner/Oracle role - high capability, used for planning and complex reasoning.</summary>
    Planner,
    /// <summary>Executor/Worker role - fast, used for routine execution.</summary>
    Executor
}

/// <summary>
/// Configuration for the dual LLM pattern.
/// </summary>
public class DualLLMConfiguration
{
    /// <summary>Unique identifier for this configuration.</summary>
    public string ConfigurationId { get; init; } = Guid.NewGuid().ToString();

    /// <summary>Model ID for the planner role.</summary>
    public required string PlannerModelId { get; init; }

    /// <summary>Model ID for the executor role.</summary>
    public required string ExecutorModelId { get; init; }

    /// <summary>Maximum planning iterations before escalating.</summary>
    public int MaxPlanningIterations { get; init; } = 3;

    /// <summary>Maximum execution steps per plan.</summary>
    public int MaxExecutionSteps { get; init; } = 10;

    /// <summary>Whether to allow executor to request planner assistance.</summary>
    public bool AllowExecutorEscalation { get; init; } = true;

    /// <summary>Complexity threshold for routing to planner vs executor.</summary>
    public double ComplexityThreshold { get; init; } = 0.7;

    /// <summary>Whether to validate executor outputs with planner.</summary>
    public bool ValidateExecutorOutputs { get; init; } = false;

    /// <summary>Sample rate for validation (0.0 - 1.0).</summary>
    public double ValidationSampleRate { get; init; } = 0.1;
}

/// <summary>
/// A plan generated by the planner.
/// </summary>
public class ExecutionPlan
{
    /// <summary>Unique identifier for this plan.</summary>
    public string PlanId { get; init; } = Guid.NewGuid().ToString();

    /// <summary>The original task description.</summary>
    public required string TaskDescription { get; init; }

    /// <summary>Steps to execute.</summary>
    public IReadOnlyList<PlanStep> Steps { get; init; } = Array.Empty<PlanStep>();

    /// <summary>Expected outcome.</summary>
    public string? ExpectedOutcome { get; init; }

    /// <summary>Confidence score (0.0 - 1.0).</summary>
    public double Confidence { get; init; }

    /// <summary>Planning iterations used.</summary>
    public int IterationsUsed { get; init; }

    /// <summary>When the plan was created.</summary>
    public DateTimeOffset CreatedAt { get; init; }

    /// <summary>Metadata from planning.</summary>
    public Dictionary<string, string> Metadata { get; init; } = new();
}

/// <summary>
/// A step in an execution plan.
/// </summary>
public class PlanStep
{
    /// <summary>Step number.</summary>
    public int StepNumber { get; init; }

    /// <summary>Description of the step.</summary>
    public required string Description { get; init; }

    /// <summary>Tool or action to use.</summary>
    public string? ToolId { get; init; }

    /// <summary>Input parameters (JSON).</summary>
    public string? InputParameters { get; init; }

    /// <summary>Expected output description.</summary>
    public string? ExpectedOutput { get; init; }

    /// <summary>Dependencies on previous steps.</summary>
    public IReadOnlyList<int> DependsOn { get; init; } = Array.Empty<int>();

    /// <summary>Whether this step requires planner involvement.</summary>
    public bool RequiresPlanner { get; init; }

    /// <summary>Estimated complexity (0.0 - 1.0).</summary>
    public double Complexity { get; init; }
}

/// <summary>
/// Result of step execution.
/// </summary>
public class StepExecutionResult
{
    /// <summary>The step that was executed.</summary>
    public required int StepNumber { get; init; }

    /// <summary>Whether execution succeeded.</summary>
    public required bool Success { get; init; }

    /// <summary>Output from execution.</summary>
    public string? Output { get; init; }

    /// <summary>Error message if failed.</summary>
    public string? ErrorMessage { get; init; }

    /// <summary>Whether escalation to planner was needed.</summary>
    public bool EscalatedToPlanner { get; init; }

    /// <summary>Execution duration in milliseconds.</summary>
    public double DurationMs { get; init; }

    /// <summary>Which model executed the step.</summary>
    public required string ExecutedBy { get; init; }
}

/// <summary>
/// Request to classify task complexity.
/// </summary>
public class ComplexityClassificationRequest
{
    /// <summary>The task description.</summary>
    public required string TaskDescription { get; init; }

    /// <summary>Context about available tools.</summary>
    public IReadOnlyList<string> AvailableTools { get; init; } = Array.Empty<string>();

    /// <summary>Historical task performance (for learning).</summary>
    public IReadOnlyList<string>? HistoricalContext { get; init; }
}

/// <summary>
/// Result of complexity classification.
/// </summary>
public class ComplexityClassificationResult
{
    /// <summary>Estimated complexity (0.0 - 1.0).</summary>
    public required double Complexity { get; init; }

    /// <summary>Recommended role for handling.</summary>
    public required LLMRole RecommendedRole { get; init; }

    /// <summary>Reason for classification.</summary>
    public string? Reason { get; init; }

    /// <summary>Estimated steps to complete.</summary>
    public int EstimatedSteps { get; init; }

    /// <summary>Tools that will likely be needed.</summary>
    public IReadOnlyList<string> LikelyTools { get; init; } = Array.Empty<string>();
}

/// <summary>
/// Port for dual LLM orchestration (Planner/Executor pattern).
/// Implements the "Dual LLM Pattern" for cost-effective execution.
/// </summary>
/// <remarks>
/// This port separates planning from execution, using a high-capability model
/// for complex reasoning and planning, and a faster/cheaper model for
/// routine execution. This optimizes cost while maintaining quality.
/// </remarks>
public interface IDualLLMPort
{
    /// <summary>
    /// Classifies task complexity to determine routing.
    /// </summary>
    /// <param name="request">The classification request.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The classification result.</returns>
    Task<ComplexityClassificationResult> ClassifyComplexityAsync(
        ComplexityClassificationRequest request,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Creates an execution plan using the planner model.
    /// </summary>
    /// <param name="taskDescription">The task to plan.</param>
    /// <param name="context">Additional context.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The execution plan.</returns>
    Task<ExecutionPlan> CreatePlanAsync(
        string taskDescription,
        Dictionary<string, string>? context = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Executes a single step using the appropriate model.
    /// </summary>
    /// <param name="plan">The plan containing the step.</param>
    /// <param name="stepNumber">The step to execute.</param>
    /// <param name="previousResults">Results from previous steps.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The step execution result.</returns>
    Task<StepExecutionResult> ExecuteStepAsync(
        ExecutionPlan plan,
        int stepNumber,
        IReadOnlyList<StepExecutionResult>? previousResults = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Executes a complete plan.
    /// </summary>
    /// <param name="plan">The plan to execute.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Results for all steps.</returns>
    Task<IReadOnlyList<StepExecutionResult>> ExecutePlanAsync(
        ExecutionPlan plan,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Requests planner assistance for an executor stuck on a step.
    /// </summary>
    /// <param name="plan">The current plan.</param>
    /// <param name="stuckStep">The step that's stuck.</param>
    /// <param name="errorContext">Error or context about why it's stuck.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Revised step or alternative approach.</returns>
    Task<PlanStep> RequestPlannerAssistanceAsync(
        ExecutionPlan plan,
        int stuckStep,
        string errorContext,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Validates executor output using planner (spot-check).
    /// </summary>
    /// <param name="step">The step that was executed.</param>
    /// <param name="output">The executor's output.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Whether the output is valid and any corrections.</returns>
    Task<(bool IsValid, string? Correction)> ValidateExecutorOutputAsync(
        PlanStep step,
        string output,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets or sets the dual LLM configuration.
    /// </summary>
    /// <param name="configuration">Configuration to set (null = get current).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The current configuration.</returns>
    Task<DualLLMConfiguration> ConfigureAsync(
        DualLLMConfiguration? configuration = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets usage statistics for the dual LLM pattern.
    /// </summary>
    /// <param name="since">Start time for statistics.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>Usage statistics.</returns>
    Task<DualLLMStatistics> GetStatisticsAsync(
        DateTimeOffset? since = null,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Statistics for dual LLM usage.
/// </summary>
public class DualLLMStatistics
{
    public int TotalPlans { get; init; }
    public int TotalSteps { get; init; }
    public int PlannerInvocations { get; init; }
    public int ExecutorInvocations { get; init; }
    public int EscalationsToPlanner { get; init; }
    public double EscalationRate { get; init; }
    public decimal TotalPlannerCost { get; init; }
    public decimal TotalExecutorCost { get; init; }
    public decimal EstimatedSavings { get; init; }
    public double AverageStepsPerPlan { get; init; }
    public double PlanSuccessRate { get; init; }
}
