extends:
  - recommended

rules:
  # Information rules
  info-contact: error
  info-license: error
  info-license-strict: error
  tag-description: error

  # Operation rules
  operation-description: error
  operation-tag-defined: error
  operation-operationId: error
  operation-summary: error
  operation-operationId-unique: error
  operation-operationId-url-safe: error
  operation-2xx-response: error
  operation-4xx-response: warn

  # Parameter rules
  parameter-description: error
  path-parameters-defined: error
  path-declaration-must-exist: error
  path-not-include-query: error

  # Schema rules
  no-identical-paths: error
  no-http-verbs-in-paths: error
  no-invalid-parameter-examples: error
  no-invalid-schema-examples: error
  no-invalid-media-type-examples: error
  no-unused-components: warn
  no-example-value-and-externalValue: warn

  # Security rules
  security-defined: error

  # Server rules
  no-server-example.com: error
  no-server-trailing-slash: error
  no-empty-servers: off

  # Style rules
  spec-components-invalid-map-name: error
  no-ambiguous-paths: off
