namespace CognitiveMesh.ReasoningLayer.AnalyticalReasoning.Models;

/// <summary>
/// Represents the result of an analytical reasoning operation.
/// </summary>
public class AnalyticalResult
{
    /// <summary>
    /// The original query that initiated the analysis.
    /// </summary>
    public string Query { get; set; } = string.Empty;

    /// <summary>
    /// The detailed analysis report generated by the reasoner.
    /// </summary>
    public string AnalysisReport { get; set; } = string.Empty;
}
